let product = [
  {
    id: 1,
    name: "iPhone 15 pro max",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iphone/iphone_15_product.jpg",
    category: "Phone",
    content:
      "Explore and Download the Apple iphone 15 Black Smartphone PNG available as a Royalty-Free Vector on toppng. Enhance your project with this stunning graphic and discover a wide range of vectors, icons, and clipart graphics wi",
  },
  {
    id: 2,
    name: "iPhone 14 pro max",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iphone/iphone_14_product.jpg",
    category: "Phone",
    content:
      "Achetez votre nouveau téléphone Apple iPhone 14 bleu 128Go et profitez d'avantages avec Orange !",
  },
  {
    id: 3,
    name: "iPhone 13 pro max",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iphone/iphone_13_banner_product_19.jpeg",
    category: "Phone",
    content:
      "DOWN PAYMENT EST. $84NO CREDIT NEEDED FINANCELEASE-TO-OWN SPECIFICATIONS: Display: 6.1-inch Super Retina XDR OLED Storage Variants: 128GB, 256G",
  },
  {
    id: 4,
    name: "iPhone 15 pro",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iphone/iphone_13_banner_product_18.webp",
    category: "Phone",
    content:
      "This item is refurbished. The Apple iPhone 15 mini has the most advanced dual-camera system ever on iPhone. Lightning-fast A15 Bionic chip. A leap in battery life.",
  },
  {
    id: 5,
    name: "iPhone 15",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iphone/iphone-13-pro-banner_product_20.webp",
    category: "Phone",
    content:
      "DOWN PAYMENT EST. $84NO CREDIT NEEDED FINANCELEASE-TO-OWN SPECIFICATIONS: Display: 6.1-inch Super Retina XDR OLED Storage Variants: 128GB, 256G",
  },

  // iphone

  {
    id: 6,
    name: "MacBook Airs",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-mac/mac_product_2.jpg",
    category: "Mac",
  },
  {
    id: 7,
    name: "MacBook Airs 2",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-mac/mac_product_1.jpg",
    category: "Mac",
  },
  {
    id: 8,
    name: "iMac",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-mac/imac_banner_product-10.jpg",
    category: "Mac",
  },

  {
    id: 9,
    name: "Mac Mini",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-mac/MacMini-banner-product-11.jpg",
    category: "Mac",
  },
  {
    id: 10,
    name: "Mac Pro",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-mac/mac-pro-banner-produc-12.jpg",
    category: "Mac",
  },
  // Mac

  {
    id: 11,
    name: "AirPods 1",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-airpods/airpod-banner-product-1.webp",
    category: "AirPods",
  },
  {
    id: 12,
    name: "AirPods 2",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-airpods/airpod_product_2.jpg",
    category: "AirPods",
  },
  {
    id: 13,
    name: "AirPods 3",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-airpods/airpod_product_1.jpg",
    category: "AirPods",
  },
  {
    id: 14,
    name: "AirPods Pro",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-airpods/airpod-banner-product-4.jpg",
    category: "AirPods",
  },
  {
    id: 15,
    name: "AirPods Pro 2",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-airpods/airpod-banner-product-5.jpg",
    category: "AirPods",
  },

  // AirPods

  {
    id: 16,
    name: "Apple Watch Series 1 ",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-watch/Apple_Watch_banner_product_1.jpg",
    category: "Watch",
  },
  {
    id: 17,
    name: "Apple Watch Series 2",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-watch/Apple_Watch_banner_product_2.png",
    category: "Watch",
  },
  {
    id: 18,
    name: "Apple Watch Series 3",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-watch/apple-watch-banner_product_3.jpg",
    category: "Watch",
  },
  {
    id: 19,
    name: "Apple Watch series 4",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-watch/apple_watch_banner_product-4.png",
    category: "Watch",
  },
  {
    id: 20,
    name: "Apple Watch series 5",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-watch/apple-watch-banner-product-5.png",
    category: "Watch",
  },
  // Apple Watch

  {
    id: 21,
    name: "iPad",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iPad/ipad__banner_product_1.png",
    category: "iPad",
  },
  {
    id: 22,
    name: "iPad",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iPad/ipad_product_1.jpg",
    category: "iPad",
  },
  {
    id: 23,
    name: "iPad",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iPad/ipad-banner-product-3.jpg",
    category: "iPad",
  },
  {
    id: 24,
    name: "iPad",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iPad/ipad_product.jpg",
    category: "iPad",
  },
  {
    id: 25,
    name: "iPad",
    cost: 45000000,
    stock: 100,
    image: "../assets/image-iPad/ipad_product_3.jpg",
    category: "iPad",
  },
  //  iPad

  {
    id: 26,
    name: "AirTags 1",
    cost: 45000000,
    stock: 100,
    image: "../assets/airtag/airtags-banner-product-1.jpeg",
    category: "AirTags",
  },
  {
    id: 27,
    name: "AirTag 2",
    cost: 45000000,
    stock: 100,
    image: "../assets/airtag/airtags-banner-product-2.jpg",
    category: "AirTags",
  },
  {
    id: 28,
    name: "AirTag 3",
    cost: 45000000,
    stock: 100,
    image: "../assets/airtag/airtag-banner-product-3.jpg",
    category: "AirTags",
  },
  {
    id: 29,
    name: "AirTag Pro",
    cost: 45000000,
    stock: 100,
    image: "../assets/airtag/airtag_product_2.jpg",
    category: "AirTags",
  },
  {
    id: 30,
    name: "AirTag",
    cost: 45000000,
    stock: 100,
    image: "../assets/airtag/airtags-banner-product-5.jpg",
    category: "AirTags",
  },

  //   airtag

  {
    id: 31,
    name: "bumper",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/phu_kien_banner_phu_kien_1.png",
    category: "phukien",
  },
  {
    id: 32,
    name: "AirPod",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/phu_kien_banner_phu_kien_2.png",
    category: "phukien",
  },
  {
    id: 33,
    name: "Music",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/apple_banner_phu_kien_3.png",
    category: "phukien",
  },
  {
    id: 34,
    name: "Wallet",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/MT5F3_banner_phu_kien_7.png",
    category: "phukien",
  },
  {
    id: 35,
    name: "Strap",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/MU7V2_banner_phu_kien_6.png",
    category: "phukien",
  },
  {
    id: 36,
    name: "Charger",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/MT263_banner_phụ_kien_5.png",
    category: "phukien",
  },
  {
    id: 37,
    name: "Charger",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/MT3Y3ref_banner_phu_kien_8.png",
    category: "phukien",
  },
  {
    id: 38,
    name: "Charger",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/ML763_banner_phu_kien_9.png",
    category: "phukien",
  },
  {
    id: 39,
    name: "AirTag Pro",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/MUWA3_banner_phu_kien_10.png",
    category: "phukien",
  },
  {
    id: 40,
    name: "bumper",
    cost: 45000000,
    stock: 100,
    image: "../assets/image_phu_kien/MQDU3_banner_phu_kien_11.png",
    category: "phukien",
  },

  // phuj kien

  {
    id: 41,
    name: "Apple Watch 1",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/apple_watch_product_1.jpg",
    category: "Product",
  },
  {
    id: 42,
    name: "Apple Watch 2",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/apple_watch_product_2.jpg",
    category: "Product",
  },
  {
    id: 43,
    name: "MacBook Pro",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/macbook_product_4.jpg",
    category: "Product",
  },
  {
    id: 44,
    name: "iPhone 15",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/iphone_product_5.jpg",
    category: "Product",
  },
  {
    id: 45,
    name: "iPhone 14",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/iphone_banner_product_6.jpg",
    category: "Product",
  },
  {
    id: 46,
    name: "iPad Mini",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/ipad-mini-banner-product-7.jpg",
    category: "Product",
  },
  {
    id: 47,
    name: "iPad Air",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/ipad-air-2022-banner-product-8.jpg",
    category: "Product",
  },
  {
    id: 48,
    name: "iPhone 15 Pro Max",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/iPhone_15_Pro_Max_9.jpg",
    category: "Product",
  },
  {
    id: 49,
    name: "MacBook",
    cost: 45000000,
    stock: 100,
    image: "../assets/product_new_product/Mac_book_product_10.jpg",
    category: "Product",
  },
];

if (!JSON.parse(localStorage.getItem("product_new"))) {
  localStorage.setItem("product_new", JSON.stringify(product));
}
// // localStorage.setItem("product_new", JSON.stringify(product));

// let login = [
//   {
//     id: 1,
//     name: "trannhuphuc",
//     email: "trannhuphuc@gmail.com",
//     password: "trannhuphuc",
//     role: 1,
//     cart: [],
//     status: 1,
//   },
// ];
// if (!JSON.parse(localStorage.getItem("login"))) {
//   localStorage.setItem("login", JSON.stringify(login));
// }
